### ISSUE TITLE
How to deal with OpenVidu Certificate when testing on different devices

### ISSUE THREAD

**Issue by VivekChoudhary128** [OpenVidu/openvidu.io-docs#8] opened 2019-02-09 08:15 UTC
I've deployed my 2.8.0 version of openvidu-server on ubuntu which is on one of my machines in my network. (**suppose it is running on 192.168.1.217:4443**)

and I'm using node.js + react.js as my front end which i'm running on different machine same network http://localhost:3000. (suppose this machine has an ip **192.168.1.218**)

my problem arises when my server side of the app (node.js) tries to get the token from the machine running at **192.168.1.217:4443**.

![image](https://user-images.githubusercontent.com/26624903/52518438-891f4d00-2c70-11e9-8ca0-22d4426ac777.png)

Even though the server is getting the request from my node and even getting the token back 

![image](https://user-images.githubusercontent.com/26624903/52518552-00a1ac00-2c72-11e9-8ced-350ccfcd3498.png)

I'm using chrome for testing, and I've found a weird workaround which is to import the openvidu certificate in my browser (i find the certificate at 192.168.1.217:4443), by following these [steps](https://superuser.com/questions/1083766/how-do-i-deal-with-neterr-cert-authority-invalid-in-chrome)
even though it works for sometimes, but most of the time i have to insecurely start my chrome by: 

**start chrome --unsafely-treat-insecure-origin-as-secure="http://192.168.1.218:3000" dir=/test/only/profile/dir**  if i want to test by using any other device, things gets worse if i want to test by phone (i can't).

Is there anything that i'm missing here that my app isn't able to create a secure web-socket.

P.S. thanks for the amazing effort you've putted in OpenVidu ;)

**Comment by pabloFuente** [comment] 2019-02-09 11:41
So, the problem is in your client side, when trying to establish the secure websocket with OpenVidu Server. Your node server is able to properly create sessions and tokens, but your browsers throw that error when calling `Session.connect(token)`

First of all, if you are going to connect to your app through any url different than localhost, then it is very important to serve it with ssl. So, do not connect to it through http://192.168.1.218:3000 but from https://192.168.1.218:3000

Secondly, you should simply need to connect to https://192.168.1.217:4443 and accept OpenVidu Server self-signed certificate once for the websocket to work. That only needs to be done for the first time.

**Comment by VivekChoudhary128** [comment] 2019-02-09 12:25
thanks for reply pablo, 

actually i can't access the app when i try it with **https** when using from other device, it has to be **http**. 

and i guess i was wrong about importing and exporting certificate, my guesses were that I needed to import them whenever i want to test it out on any new device, but as you said i only need to click proceed.

however, on the second note, when i'm going to deploy my app , I don't want my users to click proceed (even though it is one time).

is there any workaround to it when we deploy the app? do we deploy the certificate along with the app? or is there some thing I'm getting wrong (pardon me i'm fairly new)

**Comment by pabloFuente** [comment] 2019-02-09 12:33
To access your react app on https, of course you have to serve it through https. Whatever server you are using to serve it, just initialize it with ssl option.

And when deploying your app, for sure you'll need a valid domain name and certificate. You'll have to set the certificate in your app as you would do with any other web, and you'll have to set the certificate in OpenVidu Server: https://openvidu.io/docs/deployment/deploying-ubuntu/#using-your-own-certificate

**Comment by VivekChoudhary128** [comment] 2019-02-09 13:22
Thank you so much pablo for your helpful words.
I'll ping you personally when the app is done.

thanks again for your help and the amazing work you guys have putted in this.

**Comment by pabloFuente** [comment] 2019-02-09 13:27
Glad I helped. Closing this issue for now

**Closed as completed by pabloFuente** 2019-02-09 13:27 UTC
